version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0
  sonarcloud: socialtables/sonarcloud@1.4.0

workflows:
  build-and-deploy:
    jobs:
      - sonarcloud/scan:
          cache-version: v0
          github-project-slug: goldenvobla42/locallibrary
          project-key: dsfhjskfiuehrfenriu5_locallibrary
      - aws-ecr/build_and_push_image:
          filters:
            branches:
              only:
                - main
          context: aws-dev
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
                role_session_name: session-role
          profile_name: OIDC-USER
          account_id: ${ACCOUNT_ID}
          region: ${AWS_REGION}
          create_repo: true
          repo: ${MY_APP_PREFIX}
          tag: latest

      - aws-ecs/deploy_service_update:
          context: aws-dev
          filters:
            branches:
              only:
                - main
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
                role_session_name: session-role
          region: ${AWS_REGION}
          cluster: ${MY_APP_PREFIX}-cluster
          family: ${MY_APP_PREFIX}-service
          profile_name: OIDC-USER
          requires:
            - aws-ecr/build_and_push_image
#
#  nightly:
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - mainf
