# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
    build:
      docker:
        - image: circleci/python:latest
      steps:
        - checkout  # Fetch your source code from GitHub
        - setup_remote_docker: # Set up Docker within the build environment
            version: 20.10.7
        - run:
            name: Build Docker Image
            command: |
              docker build -t my-django-app .
              docker images
        - deploy:
            name: Deploy to AWS Elastic Beanstalk
            command: |
              # Log in to AWS Elastic Beanstalk
              aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
              aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
              eb login --region $AWS_REGION
              eb deploy $AWS_EB_ENV


workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

