version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: circleci-ecr-demo
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy-service-update: # orb built-in job
        requires:
          - aws-ecr/build-and-push-image
        context: aws-dev
        family: '${MY_APP_PREFIX}-service'
        cluster: '${MY_APP_PREFIX}-cluster'
        container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'