version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                  profile_name: default
            - aws-cli/role_arn_setup:
                role_arn: ${AWS_ROLE}
                profile_name: default
                source_profile: default
            - run: aws sts assume-role --role_arn "arn:aws:iam::515218242798:role/ci_cd_-circleci" --role_session_name AWSCLI-Session
          context: aws-dev
          account_id: ${ACCOUNT_ID}
          region: ${AWS_REGION}
          dockerfile: Dockerfile
          path: .
          repo: ${MY_APP_PREFIX}
          create_repo: true
          tag: ${CIRCLE_SHA1}

      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ROLE}
                profile_name: "OIDC-PROFILE"
          context: aws-dev
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          #container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
          requires:
            - aws-ecr/build_and_push_image
