version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0.0

workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build_and_push_image:
            context: aws-dev
            account_id: ${ACCOUNT_ID}
            create-repo: true
            dockerfile: Dockerfile
            path: .
            repo: circleci-ecr-demo
            tag: "$CIRCLE_SHA1"

      - aws-ecs/deploy_service_update:
          context: aws-dev
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          #container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
          requires:
            - aws-ecr/build_and_push_image
