version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          context: aws-dev
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
          profile_name: OIDC-USER
          region: ${AWS_REGION}
          registry_id: ${AWS_ECR_REGISTRY_ID}
          repo: ${MY_APP_PREFIX}
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy_service_update:
          context: aws-dev
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
          cluster: ${MY_APP_PREFIX}-cluster
          container_image_name_updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${MY_APP_PREFIX}-service
          profile_name: OIDC-USER
          requires:
            - aws-ecr/build_and_push_image
