version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-ecs: circleci/aws-ecs@4.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          context: aws-dev
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
                role_session_name: session-role
          profile_name: OIDC-USER
          account_id: ${ACCOUNT_ID}
          region: ${AWS_REGION}
          create_repo: true
          repo: ${MY_APP_PREFIX}
          tag: ${CIRCLE_SHA1}

      - aws-ecs/deploy_service_update:
          context: aws-dev
          auth:
            - aws-cli/setup:
                profile_name: OIDC-USER
                role_arn: ${AWS_ROLE}
                role_session_name: session-role
          cluster: ${MY_APP_PREFIX}-cluster
          family: ${MY_APP_PREFIX}-service
          profile_name: OIDC-USER
          requires:
            - aws-ecr/build_and_push_image
